# Generated by Django 4.2.5 on 2023-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Путь к картинке"
            ),
        ),
    ]
