# Generated by Django 4.2.5 on 2023-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Изображение"),
        ),
    ]
