# Generated by Django 4.2.5 on 2023-11-25 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_news_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
