# Generated by Django 4.2.5 on 2023-10-10 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_cart_products_cart_count_cart_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
    ]
