# Generated by Django 4.2.5 on 2023-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(validators=[], verbose_name="Количество"),
        ),
    ]
