# Generated by Django 4.2.5 on 2023-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_cartitem_cart_alter_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Общая сумма"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Итоговая стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
    ]
