# Generated by Django 4.2.5 on 2023-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_cartitem_total_alter_cart_total_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
    ]
