# Generated by Django 4.2.5 on 2023-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_remove_order_products_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество товаров"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Итоговая стоимость",
            ),
        ),
    ]
