# Generated by Django 4.2.5 on 2023-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_remove_order_price_order_count_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="shop.OrderItem",
                to="shop.product",
                through_fields=("order", "product"),
            ),
        ),
    ]
